#version 430

layout(local_size_x = 256) in;

struct Particle
{
    vec4 position;
    vec4 velocity;
    vec4 color;
    vec4 data1;
    vec4 data2;
};

layout(std430, binding = 0) buffer ParticleBuffer
{
    Particle particles[];
};

uniform float deltaTime;
uniform uint maxParticles;

void main()
{
    uint id = gl_GlobalInvocationID.x;

    if (id >= maxParticles)
    return;

    Particle p = particles[id];

    if (p.data1.w <= 0.0)
    return;

    float life = p.data1.x;
    life -= deltaTime;
    p.data1.x = life;

    float gravity = p.data2.x;
    p.velocity.y -= gravity * deltaTime;


    p.velocity.x = 0.0;


    p.position.xyz += p.velocity.xyz * deltaTime;

    float maxLife = p.data1.y;
    float progress = 1.0 - (life / maxLife);
    p.color.a = mix(1.0, 0.0, progress);

    particles[id] = p;
}